# version: '3.8'

services:
  api:
    container_name: smartgrid-api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - smartgrid-dev-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  smartgrid-dev-network:
    driver: bridge 