version: '3.3'

services:
  api:
    container_name: smartgrid-api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev.proxy
      args:
        - HTTP_PROXY=http://172.16.2.254:3128
        - HTTPS_PROXY=http://172.16.2.254:3128
    ports:
      - "3010:3000"
    env_file:
      - .env.development
    environment:
      - HTTP_PROXY=http://172.16.2.254:3128
      - HTTPS_PROXY=http://172.16.2.254:3128
      - npm_config_proxy=http://172.16.2.254:3128
      - npm_config_https_proxy=http://172.16.2.254:3128
      - npm_config_strict_ssl=false
      - NO_PROXY=localhost,127.0.0.1,db,registry.npmjs.org
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - .:/usr/src/app
      - .env.development:/usr/src/app/.env
    networks:
      - smartgrid-dev-network
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3010/health"]
      interval: 10s
      timeout: 10s
      retries: 3
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: smartgrid-db-dev
    cap_add: 
      - SYS_PTRACE
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
      - MSSQL_LCID=1033
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./sql-scripts:/usr/config
    command: /bin/bash /usr/config/entrypoint.sh
    networks:
      - smartgrid-dev-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong!Passw0rd" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10

networks:
  smartgrid-dev-network:
    driver: bridge

volumes:
  sqlserver_data:
    driver: local 