FROM node:20-alpine

# Add proxy settings with default values
ARG HTTP_PROXY
ARG HTTPS_PROXY
ENV HTTP_PROXY=$HTTP_PROXY
ENV HTTPS_PROXY=$HTTPS_PROXY
ENV NO_PROXY="localhost,127.0.0.1,db"


WORKDIR /usr/src/app

# Copy package files first
COPY package*.json ./

# Configure npm to use proxy
RUN npm config set proxy $HTTP_PROXY && \
    npm config set https-proxy $HTTPS_PROXY && \
    npm config set strict-ssl false && \
    npm config set registry https://registry.npmjs.org/


# Copy source code
COPY . .
RUN npm install


EXPOSE 3010

# Use npx to ensure local CLI is used
CMD ["npm", "run", "start:dev"]